DESTINATIONS = [
    {"name": "București", "type": "moderat", "activity": "cultura", "nature": "parcuri", "budget": "mic", "region": "Europa"},
    {"name": "Paris", "type": "moderat", "activity": "cultura", "nature": "gradini", "budget": "lux", "region": "Europa"},
    {"name": "Londra", "type": "moderat", "activity": "muzee", "nature": "parcuri", "budget": "lux", "region": "Europa"},
    {"name": "Roma", "type": "cald", "activity": "istorie", "nature": "coline", "budget": "mediu", "region": "Europa"},
    {"name": "Barcelona", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Brașov", "type": "moderat", "activity": "plimbare", "nature": "munte", "budget": "mic", "region": "Europa"},
    {"name": "Praga", "type": "moderat", "activity": "istorie", "nature": "rau", "budget": "mic", "region": "Europa"},
    {"name": "Viena", "type": "moderat", "activity": "muzica", "nature": "parcuri", "budget": "mediu", "region": "Europa"},
    {"name": "Amsterdam", "type": "moderat", "activity": "party", "nature": "canale", "budget": "lux", "region": "Europa"},
    {"name": "Atena", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Lisabona", "type": "cald", "activity": "plimbare", "nature": "ocean", "budget": "mediu", "region": "Europa"},
    {"name": "Oslo", "type": "rece", "activity": "muzee", "nature": "fiorduri", "budget": "lux", "region": "Europa"},
    {"name": "Stockholm", "type": "rece", "activity": "design", "nature": "arhipelag", "budget": "lux", "region": "Europa"},
    {"name": "Copenhaga", "type": "moderat", "activity": "bici", "nature": "mare", "budget": "lux", "region": "Europa"},
    {"name": "Budapesta", "type": "moderat", "activity": "spa", "nature": "rau", "budget": "mic", "region": "Europa"},
    {"name": "Varșovia", "type": "moderat", "activity": "istorie", "nature": "parcuri", "budget": "mic", "region": "Europa"},
    {"name": "Berlin", "type": "moderat", "activity": "party", "nature": "lacuri", "budget": "mediu", "region": "Europa"},
    {"name": "Madrid", "type": "cald", "activity": "arta", "nature": "parcuri", "budget": "mediu", "region": "Europa"},
    {"name": "Reykjavik", "type": "rece", "activity": "aventura", "nature": "vulcani", "budget": "lux", "region": "Europa"},
    {"name": "Santorini", "type": "cald", "activity": "relaxare", "nature": "mare", "budget": "lux", "region": "Europa"},
    {"name": "Dubrovnik", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Venetia", "type": "moderat", "activity": "romantism", "nature": "canale", "budget": "lux", "region": "Europa"},
    {"name": "Munchen", "type": "moderat", "activity": "bere", "nature": "alpi", "budget": "mediu", "region": "Europa"},
    {"name": "Sibiu", "type": "moderat", "activity": "cultura", "nature": "munte", "budget": "mic", "region": "Europa"},
    {"name": "Timișoara", "type": "moderat", "activity": "cultura", "nature": "parcuri", "budget": "mic", "region": "Europa"},
    {"name": "Iași", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Constanța", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Galați", "type": "moderat", "activity": "plimbare", "nature": "rau", "budget": "mic", "region": "Europa"},
    {"name": "Ploiești", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Oradea", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Târgu Mureș", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Baia Mare", "type": "moderat", "activity": "plimbare", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Bacău", "type": "moderat", "activity": "plimbare", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Buzău", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Suceava", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Satu Mare", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Sfântu Gheorghe", "type": "moderat", "activity": "plimbare", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Reșița", "type": "moderat", "activity": "industrie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Arad", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Brăila", "type": "moderat", "activity": "plimbare", "nature": "rau", "budget": "mic", "region": "Europa"},
    {"name": "Birmingham", "type": "moderat", "activity": "industrie", "nature": "parcuri", "budget": "mediu", "region": "Europa"},
    {"name": "Manchester", "type": "moderat", "activity": "fotbal", "nature": "canale", "budget": "mediu", "region": "Europa"},
    {"name": "Liverpool", "type": "moderat", "activity": "muzica", "nature": "port", "budget": "mediu", "region": "Europa"},
    {"name": "Nottingham", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Cardiff", "type": "moderat", "activity": "sport", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Belfast", "type": "rece", "activity": "istorie", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Sheffield", "type": "moderat", "activity": "industrie", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Leeds", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Bristol", "type": "moderat", "activity": "arta", "nature": "rau", "budget": "mediu", "region": "Europa"},
    {"name": "Gloucester", "type": "moderat", "activity": "istorie", "nature": "canale", "budget": "mediu", "region": "Europa"},
    {"name": "Southampton", "type": "cald", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Brighton", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Bournemouth", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Oxford", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Cambridge", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Ghent", "type": "moderat", "activity": "cultura", "nature": "canale", "budget": "mediu", "region": "Europa"},
    {"name": "Antwerp", "type": "moderat", "activity": "port", "nature": "rau", "budget": "mediu", "region": "Europa"},
    {"name": "Bruges", "type": "moderat", "activity": "turism", "nature": "canale", "budget": "mediu", "region": "Europa"},
    {"name": "Namur", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Leuven", "type": "moderat", "activity": "studenti", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Antibes", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "lux", "region": "Europa"},
    {"name": "Toulouse", "type": "moderat", "activity": "aerospatial", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Montpellier", "type": "cald", "activity": "plaja", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Brest", "type": "rece", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Rouen", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mediu", "region": "Europa"},
    {"name": "Le Havre", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Brno", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Ostrava", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Katowice", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Gdansk", "type": "moderat", "activity": "cultura", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Wroclaw", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mic", "region": "Europa"},
    {"name": "Poznan", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Lodz", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Szczecin", "type": "cald", "activity": "port", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Rennes", "type": "moderat", "activity": "cultura", "nature": "marea", "budget": "mediu", "region": "Europa"},
    {"name": "Clermont-Ferrand", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Tours", "type": "moderat", "activity": "vin", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Limoges", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Perpignan", "type": "cald", "activity": "plaja", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Modena", "type": "moderat", "activity": "auto", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Parma", "type": "moderat", "activity": "gastronomie", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Bologna", "type": "moderat", "activity": "arte", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Verona", "type": "moderat", "activity": "romantism", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Trieste", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Split", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Zadar", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Bari", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Cagliari", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "mediu", "region": "Europa"},
    {"name": "Brescia", "type": "moderat", "activity": "industrie", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Genoa", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Turin", "type": "moderat", "activity": "arta", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Lecco", "type": "moderat", "activity": "munte", "nature": "lac", "budget": "mediu", "region": "Europa"},
    {"name": "Como", "type": "moderat", "activity": "lac", "nature": "munte", "budget": "mediu", "region": "Europa"},
    {"name": "Bergamo", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Padova", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Ravenna", "type": "moderat", "activity": "istorie", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Perugia", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Spoleto", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Sassari", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Trapani", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Palermo", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Catania", "type": "cald", "activity": "vulcan", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Luton", "type": "moderat", "activity": "transport", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Plymouth", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Swansea", "type": "moderat", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Aberdeen", "type": "rece", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Inverness", "type": "rece", "activity": "aventura", "nature": "munte", "budget": "mediu", "region": "Europa"},
    {"name": "Perth", "type": "rece", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Utrecht", "type": "moderat", "activity": "canale", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Eindhoven", "type": "moderat", "activity": "design", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Rotterdam", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "The Hague", "type": "moderat", "activity": "politica", "nature": "coasta", "budget": "mediu", "region": "Europa"},

    {"name": "Ljubljana", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Maribor", "type": "moderat", "activity": "vin", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Zagreb", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Rijeka", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Bergen", "type": "rece", "activity": "aventura", "nature": "munte", "budget": "lux", "region": "Europa"},
    {"name": "Trondheim", "type": "rece", "activity": "istorie", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Stavanger", "type": "rece", "activity": "port", "nature": "fjord", "budget": "mediu", "region": "Europa"},
    {"name": "Helsinki", "type": "rece", "activity": "cultura", "nature": "coasta", "budget": "lux", "region": "Europa"},
    {"name": "Turku", "type": "rece", "activity": "istorie", "nature": "insula", "budget": "mediu", "region": "Europa"},
    {"name": "Tampere", "type": "rece", "activity": "industrie", "nature": "lacul", "budget": "mediu", "region": "Europa"},
    {"name": "Espoo", "type": "rece", "activity": "tehnologie", "nature": "coasta", "budget": "lux", "region": "Europa"},
    {"name": "Tallinn", "type": "rece", "activity": "cultura", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Tartu", "type": "rece", "activity": "studenti", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Riga", "type": "rece", "activity": "cultura", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Daugavpils", "type": "rece", "activity": "industrie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Vilnius", "type": "rece", "activity": "istorie", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Kaunas", "type": "rece", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Klaipeda", "type": "rece", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Europa"},
    {"name": "Dublin", "type": "moderat", "activity": "cultura", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Cork", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Galway", "type": "moderat", "activity": "turism", "nature": "coasta", "budget": "mic", "region": "Europa"},
    {"name": "Limerick", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Waterford", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mic", "region": "Europa"},
    {"name": "Luxembourg", "type": "moderat", "activity": "finante", "nature": "dealuri", "budget": "lux", "region": "Europa"},
    {"name": "Basel", "type": "moderat", "activity": "industrie", "nature": "rau", "budget": "lux", "region": "Europa"},
    {"name": "Zurich", "type": "moderat", "activity": "finante", "nature": "lac", "budget": "lux", "region": "Europa"},
    {"name": "Geneva", "type": "moderat", "activity": "diplomatie", "nature": "lac", "budget": "lux", "region": "Europa"},
    {"name": "Lausanne", "type": "moderat", "activity": "sport", "nature": "lac", "budget": "lux", "region": "Europa"},
    {"name": "Bern", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "lux", "region": "Europa"},
    {"name": "Lucerne", "type": "moderat", "activity": "turism", "nature": "lac", "budget": "lux", "region": "Europa"},
    {"name": "Interlaken", "type": "moderat", "activity": "aventura", "nature": "munte", "budget": "lux", "region": "Europa"},
    {"name": "Innsbruck", "type": "rece", "activity": "munte", "nature": "munte", "budget": "mediu", "region": "Europa"},
    {"name": "Salzburg", "type": "moderat", "activity": "muzica", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Graz", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Linz", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Villach", "type": "rece", "activity": "munte", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Klagenfurt", "type": "rece", "activity": "lac", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Bratislava", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mediu", "region": "Europa"},
    {"name": "Košice", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Nitra", "type": "moderat", "activity": "istorie", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Banská Bystrica", "type": "moderat", "activity": "munte", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Debrecen", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Szeged", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Europa"},
    {"name": "Pecs", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Cluj-Napoca", "type": "moderat", "activity": "studenti", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Varna", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Sofia", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Plovdiv", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mediu", "region": "Europa"},
    {"name": "Burgas", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Skopje", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Ohrid", "type": "moderat", "activity": "lac", "nature": "munte", "budget": "mic", "region": "Europa"},
    {"name": "Kotor", "type": "cald", "activity": "turism", "nature": "coasta", "budget": "mic", "region": "Europa"},
    {"name": "Tirana", "type": "cald", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Durres", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Europa"},
    {"name": "Sarajevo", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Mostar", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Belgrade", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mediu", "region": "Europa"},
    {"name": "Novi Sad", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Europa"},
    {"name": "Podgorica", "type": "cald", "activity": "aventura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Pristina", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Europa"},
    {"name": "Riga", "type": "rece", "activity": "cultura", "nature": "coasta", "budget": "mediu", "region": "Europa"},
    {"name": "Tokyo", "type": "moderat", "activity": "tehnologie", "nature": "gradini", "budget": "lux", "region": "Asia"},
    {"name": "Kyoto", "type": "moderat", "activity": "temple", "nature": "padure", "budget": "mediu", "region": "Asia"},
    {"name": "Bangkok", "type": "cald", "activity": "streetfood", "nature": "rau", "budget": "mic", "region": "Asia"},
    {"name": "Phuket", "type": "cald", "activity": "plaja", "nature": "insule", "budget": "mic", "region": "Asia"},
    {"name": "Bali", "type": "cald", "activity": "yoga", "nature": "jungla", "budget": "mediu", "region": "Asia"},
    {"name": "Dubai", "type": "cald", "activity": "shopping", "nature": "desert", "budget": "lux", "region": "Asia"},
    {"name": "Abu Dhabi", "type": "cald", "activity": "cultura", "nature": "desert", "budget": "lux", "region": "Asia"},
    {"name": "Seoul", "type": "moderat", "activity": "k-pop", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Hanoi", "type": "cald", "activity": "istorie", "nature": "golf", "budget": "mic", "region": "Asia"},
    {"name": "Manila", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Asia"},
    {"name": "Mumbai", "type": "cald", "activity": "business", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "Beijing", "type": "moderat", "activity": "istorie", "nature": "zid", "budget": "mediu", "region": "Asia"},
    {"name": "Hong Kong", "type": "cald", "activity": "shopping", "nature": "golf", "budget": "lux", "region": "Asia"},
    {"name": "Malé", "type": "cald", "activity": "plaja", "nature": "atoli", "budget": "lux", "region": "Asia"},
    {"name": "Kathmandu", "type": "rece", "activity": "trekking", "nature": "himalaya", "budget": "mic", "region": "Asia"},
    {"name": "Taipei", "type": "cald", "activity": "food", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Tbilisi", "type": "moderat", "activity": "vin", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Erevan", "type": "moderat", "activity": "istorie", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Baku", "type": "moderat", "activity": "arhitectura", "nature": "mare", "budget": "mediu", "region": "Asia"},
    {"name": "Muscat", "type": "cald", "activity": "cultura", "nature": "ocean", "budget": "mediu", "region": "Asia"},
    {"name": "Doha", "type": "cald", "activity": "muzee", "nature": "golf", "budget": "lux", "region": "Asia"},
    {"name": "Colombo", "type": "cald", "activity": "ceai", "nature": "ocean", "budget": "mic", "region": "Asia"},
    {"name": "Ho Chi Minh City", "type": "cald", "activity": "scutere", "nature": "rau", "budget": "mic", "region": "Asia"},
    {"name": "Chiang Mai", "type": "moderat", "activity": "temple", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Tel Aviv", "type": "cald", "activity": "beachparty", "nature": "mare", "budget": "lux", "region": "Asia"},
    {"name": "Kuala Lumpur", "type": "cald", "activity": "shopping", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Jakarta", "type": "cald", "activity": "business", "nature": "delta", "budget": "mic", "region": "Asia"},
    {"name": "Manila", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Asia"},
    {"name": "Ulaanbaatar", "type": "rece", "activity": "cultura", "nature": "stepa", "budget": "mic", "region": "Asia"},
    {"name": "Pyongyang", "type": "rece", "activity": "istorie", "nature": "campie", "budget": "mic", "region": "Asia"},
    {"name": "Astana", "type": "rece", "activity": "modern", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Almaty", "type": "moderat", "activity": "munte", "nature": "alpi", "budget": "mediu", "region": "Asia"},
    {"name": "Tashkent", "type": "moderat", "activity": "istorie", "nature": "desert", "budget": "mic", "region": "Asia"},
    {"name": "Bishkek", "type": "moderat", "activity": "trekking", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Ashgabat", "type": "cald", "activity": "arhitectura", "nature": "desert", "budget": "lux", "region": "Asia"},
    {"name": "Dushanbe", "type": "moderat", "activity": "cultura", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Singapore", "type": "cald", "activity": "food", "nature": "gradini", "budget": "lux", "region": "Asia"},
    {"name": "Hefei", "type": "moderat", "activity": "istorie", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Shanghai", "type": "moderat", "activity": "tehnologie", "nature": "fluviu", "budget": "lux", "region": "Asia"},
    {"name": "Guangzhou", "type": "cald", "activity": "shopping", "nature": "fluviu", "budget": "mediu", "region": "Asia"},
    {"name": "Shenzhen", "type": "cald", "activity": "tehnologie", "nature": "mare", "budget": "lux", "region": "Asia"},
    {"name": "Chengdu", "type": "moderat", "activity": "panda", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Wuhan", "type": "moderat", "activity": "cultura", "nature": "fluviu", "budget": "mediu", "region": "Asia"},
    {"name": "Hangzhou", "type": "moderat", "activity": "lacuri", "nature": "gradini", "budget": "mediu", "region": "Asia"},
    {"name": "Suzhou", "type": "moderat", "activity": "gradini", "nature": "canale", "budget": "mediu", "region": "Asia"},
    {"name": "Nanjing", "type": "moderat", "activity": "istorie", "nature": "fluviu", "budget": "mediu", "region": "Asia"},
    {"name": "Sejong", "type": "moderat", "activity": "administratie", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Busan", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu", "region": "Asia"},
    {"name": "Incheon", "type": "moderat", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Asia"},
    {"name": "Vientiane", "type": "cald", "activity": "cultura", "nature": "rau", "budget": "mic", "region": "Asia"},
    {"name": "Siem Reap", "type": "cald", "activity": "temple", "nature": "padure", "budget": "mic", "region": "Asia"},
    {"name": "Mandalay", "type": "cald", "activity": "cultura", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Kochi", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "Thimphu", "type": "rece", "activity": "trekking", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Malang", "type": "cald", "activity": "plaja", "nature": "jungla", "budget": "mic", "region": "Asia"},
    {"name": "Bandung", "type": "moderat", "activity": "munte", "nature": "jungla", "budget": "mediu", "region": "Asia"},
    {"name": "Medan", "type": "cald", "activity": "plaja", "nature": "delta", "budget": "mic", "region": "Asia"},
    {"name": "Pattaya", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "Sapporo", "type": "rece", "activity": "schi", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Hiroshima", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mediu", "region": "Asia"},
    {"name": "Osaka", "type": "moderat", "activity": "cultura", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Nagoya", "type": "moderat", "activity": "industrie", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Kanazawa", "type": "moderat", "activity": "gradini", "nature": "dealuri", "budget": "mediu", "region": "Asia"},
    {"name": "Nara", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mediu", "region": "Asia"},
    {"name": "Fukuoka", "type": "moderat", "activity": "shopping", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Kobe", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Sendai", "type": "moderat", "activity": "cultura", "nature": "padure", "budget": "mediu", "region": "Asia"},
    {"name": "Taichung", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Kaohsiung", "type": "cald", "activity": "port", "nature": "mare", "budget": "mediu", "region": "Asia"},
    {"name": "Ulsan", "type": "moderat", "activity": "industrie", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Gwangju", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "Asia"},
    {"name": "Jeju", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "mediu", "region": "Asia"},
    {"name": "Yangzhou", "type": "moderat", "activity": "gradini", "nature": "fluviu", "budget": "mediu", "region": "Asia"},
    {"name": "Qingdao", "type": "cald", "activity": "plaja", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Dalian", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Xiamen", "type": "cald", "activity": "plaja", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Ningbo", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "Asia"},
    {"name": "Chongqing", "type": "cald", "activity": "cultura", "nature": "fluviu", "budget": "mediu", "region": "Asia"},
    {"name": "Shenyang", "type": "rece", "activity": "istorie", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Harbin", "type": "rece", "activity": "iarna", "nature": "padure", "budget": "mediu", "region": "Asia"},
    {"name": "Urumqi", "type": "rece", "activity": "cultura", "nature": "desert", "budget": "mediu", "region": "Asia"},
    {"name": "Xi'an", "type": "moderat", "activity": "istorie", "nature": "campie", "budget": "mediu", "region": "Asia"},
    {"name": "Lhasa", "type": "rece", "activity": "istorie", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Paro", "type": "rece", "activity": "cultura", "nature": "munte", "budget": "mediu", "region": "Asia"},
    {"name": "Luang Prabang", "type": "cald", "activity": "cultura", "nature": "rau", "budget": "mic", "region": "Asia"},
    {"name": "Chiang Rai", "type": "cald", "activity": "temple", "nature": "dealuri", "budget": "mic", "region": "Asia"},
    {"name": "Siem Reap", "type": "cald", "activity": "temple", "nature": "padure", "budget": "mic", "region": "Asia"},
    {"name": "Phnom Penh", "type": "cald", "activity": "istorie", "nature": "fluviu", "budget": "mic", "region": "Asia"},
    {"name": "Yangon", "type": "cald", "activity": "istorie", "nature": "rau", "budget": "mic", "region": "Asia"},
    {"name": "Mandalay", "type": "cald", "activity": "cultura", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Thiruvananthapuram", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "Goa", "type": "cald", "activity": "plaja", "nature": "coasta", "budget": "mic", "region": "Asia"},
    {"name": "Chittagong", "type": "cald", "activity": "port", "nature": "coasta", "budget": "mic", "region": "Asia"},
    {"name": "Dhaka", "type": "cald", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "Asia"},
    {"name": "Pokhara", "type": "moderat", "activity": "trekking", "nature": "munte", "budget": "mic", "region": "Asia"},
    {"name": "Galle", "type": "cald", "activity": "istorie", "nature": "coasta", "budget": "mic", "region": "Asia"},
    {"name": "Colombo", "type": "cald", "activity": "ceai", "nature": "ocean", "budget": "mic", "region": "Asia"},
    {"name": "Hua Hin", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "Da Nang", "type": "cald", "activity": "plaja", "nature": "fluviu", "budget": "mic", "region": "Asia"},
    {"name": "Hoi An", "type": "cald", "activity": "cultura", "nature": "fluviu", "budget": "mic", "region": "Asia"},
    {"name": "Luang Namtha", "type": "cald", "activity": "aventura", "nature": "jungla", "budget": "mic", "region": "Asia"},
    {"name": "Penang", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "mic", "region": "Asia"},
    {"name": "Malacca", "type": "cald", "activity": "istorie", "nature": "coasta", "budget": "mic", "region": "Asia"},
    {"name": "Yogyakarta", "type": "cald", "activity": "temple", "nature": "campie", "budget": "mic", "region": "Asia"},
    {"name": "Surabaya", "type": "cald", "activity": "shopping", "nature": "mare", "budget": "mic", "region": "Asia"},
    {"name": "New York", "type": "moderat", "activity": "show", "nature": "parcuri", "budget": "lux", "region": "America"},
    {"name": "Los Angeles", "type": "cald", "activity": "filme", "nature": "plaja", "budget": "lux", "region": "America"},
    {"name": "Miami", "type": "cald", "activity": "party", "nature": "ocean", "budget": "lux", "region": "America"},
    {"name": "San Francisco", "type": "moderat", "activity": "tech", "nature": "golf", "budget": "lux", "region": "America"},
    {"name": "Las Vegas", "type": "cald", "activity": "cazino", "nature": "desert", "budget": "mediu", "region": "America"},
    {"name": "Chicago", "type": "rece", "activity": "arhitectura", "nature": "lac", "budget": "mediu", "region": "America"},
    {"name": "Toronto", "type": "rece", "activity": "muzee", "nature": "lac", "budget": "mediu", "region": "America"},
    {"name": "Vancouver", "type": "moderat", "activity": "aventura", "nature": "munte", "budget": "lux", "region": "America"},
    {"name": "Mexico City", "type": "cald", "activity": "istorie", "nature": "vulcan", "budget": "mic", "region": "America"},
    {"name": "Cancun", "type": "cald", "activity": "plaja", "nature": "jungla", "budget": "mediu", "region": "America"},
    {"name": "Rio de Janeiro", "type": "cald", "activity": "carnaval", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Buenos Aires", "type": "moderat", "activity": "tango", "nature": "rau", "budget": "mic", "region": "America"},
    {"name": "Lima", "type": "cald", "activity": "gastronomie", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Santiago", "type": "moderat", "activity": "vin", "nature": "anzi", "budget": "mediu", "region": "America"},
    {"name": "Havana", "type": "cald", "activity": "muzica", "nature": "plaja", "budget": "mic", "region": "America"},
    {"name": "Quebec City", "type": "rece", "activity": "istorie", "nature": "rau", "budget": "mediu", "region": "America"},
    {"name": "Montreal", "type": "rece", "activity": "jazz", "nature": "insulă", "budget": "mediu", "region": "America"},
    {"name": "Seattle", "type": "rece", "activity": "cafea", "nature": "munte", "budget": "lux", "region": "America"},
    {"name": "New Orleans", "type": "cald", "activity": "jazz", "nature": "rau", "budget": "mediu", "region": "America"},
    
    {"name": "Boston", "type": "rece", "activity": "istorie", "nature": "parcuri", "budget": "mediu", "region": "America"},
    {"name": "Philadelphia", "type": "moderat", "activity": "istorie", "nature": "parcuri", "budget": "mediu", "region": "America"},
    {"name": "Atlanta", "type": "cald", "activity": "cultura", "nature": "padure", "budget": "mediu", "region": "America"},
    {"name": "Orlando", "type": "cald", "activity": "parcuri", "nature": "lacul", "budget": "mediu", "region": "America"},
    {"name": "Dallas", "type": "cald", "activity": "business", "nature": "campie", "budget": "mediu", "region": "America"},
    {"name": "Houston", "type": "cald", "activity": "spatiu", "nature": "campie", "budget": "mediu", "region": "America"},
    {"name": "Austin", "type": "cald", "activity": "muzica", "nature": "campie", "budget": "mediu", "region": "America"},
    {"name": "Phoenix", "type": "cald", "activity": "desert", "nature": "desert", "budget": "mediu", "region": "America"},
    {"name": "Denver", "type": "moderat", "activity": "munte", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Portland", "type": "moderat", "activity": "cafea", "nature": "padure", "budget": "mediu", "region": "America"},
    {"name": "Minneapolis", "type": "rece", "activity": "lacuri", "nature": "lac", "budget": "mediu", "region": "America"},
    {"name": "Salt Lake City", "type": "moderat", "activity": "munte", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Miami Beach", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Fort Lauderdale", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "San Diego", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Santa Monica", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Honolulu", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "America"},
    {"name": "Anchorage", "type": "rece", "activity": "aventura", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Fairbanks", "type": "rece", "activity": "iarna", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Ottawa", "type": "rece", "activity": "cultura", "nature": "lac", "budget": "mediu", "region": "America"},
    {"name": "Winnipeg", "type": "rece", "activity": "muzee", "nature": "lac", "budget": "mediu", "region": "America"},
    {"name": "Calgary", "type": "moderat", "activity": "munte", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Edmonton", "type": "moderat", "activity": "festival", "nature": "campie", "budget": "mediu", "region": "America"},
    {"name": "Quebec", "type": "rece", "activity": "istorie", "nature": "rau", "budget": "mediu", "region": "America"},
    {"name": "Halifax", "type": "rece", "activity": "cultura", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "St. John's", "type": "rece", "activity": "aventura", "nature": "coasta", "budget": "mediu", "region": "America"},
    {"name": "Bermuda City", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "America"},
    {"name": "Belize City", "type": "cald", "activity": "plaja", "nature": "jungla", "budget": "mic", "region": "America"},
    {"name": "San Jose", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Managua", "type": "cald", "activity": "istorie", "nature": "lac", "budget": "mic", "region": "America"},
    {"name": "Panama City", "type": "cald", "activity": "canal", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Cartagena", "type": "cald", "activity": "istorie", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Bogotá", "type": "moderat", "activity": "cultura", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Medellín", "type": "cald", "activity": "cultura", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Quito", "type": "moderat", "activity": "istorie", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Guayaquil", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "La Paz", "type": "rece", "activity": "munte", "nature": "andi", "budget": "mic", "region": "America"},
    {"name": "Sucre", "type": "moderat", "activity": "istorie", "nature": "campie", "budget": "mic", "region": "America"},
    {"name": "Córdoba", "type": "moderat", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "America"},
    {"name": "Recife", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Fortaleza", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Salvador", "type": "cald", "activity": "cultura", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Brasília", "type": "cald", "activity": "administratie", "nature": "campie", "budget": "mediu", "region": "America"},
    {"name": "Manaus", "type": "cald", "activity": "jungla", "nature": "fluviu", "budget": "mic", "region": "America"},
    {"name": "Belém", "type": "cald", "activity": "jungla", "nature": "fluviu", "budget": "mic", "region": "America"},
    {"name": "Porto Alegre", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mediu", "region": "America"},
    {"name": "Curitiba", "type": "moderat", "activity": "gradini", "nature": "padure", "budget": "mediu", "region": "America"},
    {"name": "Asunción", "type": "cald", "activity": "istorie", "nature": "rau", "budget": "mic", "region": "America"},
    {"name": "Santa Cruz de la Sierra", "type": "cald", "activity": "aventura", "nature": "jungla", "budget": "mic", "region": "America"},
    {"name": "San Salvador", "type": "cald", "activity": "cultura", "nature": "campie", "budget": "mic", "region": "America"},
    {"name": "Guatemala City", "type": "cald", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "America"},
    {"name": "Honduras City", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Tegucigalpa", "type": "cald", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "America"},
    {"name": "Kingston", "type": "cald", "activity": "muzica", "nature": "ocean", "budget": "mic", "region": "America"},
    {"name": "Nassau", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Providenciales", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "mediu", "region": "America"},
    {"name": "Barbados City", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "lux", "region": "America"},
    {"name": "Kingstown", "type": "cald", "activity": "aventura", "nature": "coasta", "budget": "mic", "region": "America"},
    {"name": "Bridgetown", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "America"},
    {"name": "Paramaribo", "type": "cald", "activity": "cultura", "nature": "jungla", "budget": "mic", "region": "America"},
    {"name": "Georgetown", "type": "cald", "activity": "aventura", "nature": "jungla", "budget": "mic", "region": "America"},
    {"name": "Cayenne", "type": "cald", "activity": "aventura", "nature": "jungla", "budget": "mic", "region": "America"},
    {"name": "Montevideo", "type": "moderat", "activity": "plaja", "nature": "rau", "budget": "mediu", "region": "America"},
    {"name": "Rosario", "type": "moderat", "activity": "cultura", "nature": "rau", "budget": "mic", "region": "America"},
    {"name": "Bariloche", "type": "moderat", "activity": "munte", "nature": "lacul", "budget": "mediu", "region": "America"},
    {"name": "Mendoza", "type": "moderat", "activity": "vin", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Punta del Este", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "lux", "region": "America"},
    {"name": "Salta", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "America"},
    {"name": "Iquitos", "type": "cald", "activity": "jungla", "nature": "fluviu", "budget": "mic", "region": "America"},
    {"name": "Arequipa", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "America"},
    {"name": "Cusco", "type": "moderat", "activity": "istorie", "nature": "munte", "budget": "mic", "region": "America"},
    {"name": "Valparaíso", "type": "moderat", "activity": "port", "nature": "coasta", "budget": "mediu", "region": "America"},
    {"name": "Viña del Mar", "type": "cald", "activity": "plaja", "nature": "coasta", "budget": "mediu", "region": "America"},
    {"name": "Puebla", "type": "moderat", "activity": "istorie", "nature": "dealuri", "budget": "mic", "region": "America"},
    {"name": "Guadalajara", "type": "cald", "activity": "cultura", "nature": "dealuri", "budget": "mediu", "region": "America"},
    {"name": "Monterrey", "type": "cald", "activity": "business", "nature": "munte", "budget": "mediu", "region": "America"},
    {"name": "Sydney", "type": "cald", "activity": "surfing", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Melbourne", "type": "moderat", "activity": "cafea", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Auckland", "type": "moderat", "activity": "navigatie", "nature": "vulcani", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Cape Town", "type": "cald", "activity": "vin", "nature": "munte", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Cairo", "type": "cald", "activity": "piramide", "nature": "nile", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Marrakech", "type": "cald", "activity": "bazar", "nature": "desert", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Casablanca", "type": "cald", "activity": "ocean", "nature": "plaja", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Nairobi", "type": "cald", "activity": "safari", "nature": "savana", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Zanzibar", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Antalya", "type": "cald", "activity": "resort", "nature": "mare", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Perth", "type": "cald", "activity": "soare", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Brisbane", "type": "cald", "activity": "surfing", "nature": "rau", "budget": "lux", "region": "Africa & Altele"},
    
    {"name": "Johannesburg", "type": "cald", "activity": "business", "nature": "campie", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Durban", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Pretoria", "type": "cald", "activity": "istorie", "nature": "padure", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Windhoek", "type": "rece", "activity": "aventura", "nature": "desert", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Lagos", "type": "cald", "activity": "muzica", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Accra", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Dakar", "type": "cald", "activity": "cultura", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Casablanca", "type": "cald", "activity": "bazar", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Tunis", "type": "cald", "activity": "istorie", "nature": "mediterana", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Algiers", "type": "cald", "activity": "istorie", "nature": "mediterana", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Tripoli", "type": "cald", "activity": "istorie", "nature": "mediterana", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Addis Ababa", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Kigali", "type": "moderat", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Harare", "type": "cald", "activity": "cultura", "nature": "padure", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Maputo", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Luanda", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Kinshasa", "type": "cald", "activity": "muzica", "nature": "fluviu", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Brazzaville", "type": "cald", "activity": "muzica", "nature": "fluviu", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Freetown", "type": "cald", "activity": "istorie", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Monrovia", "type": "cald", "activity": "istorie", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Banjul", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Nouakchott", "type": "cald", "activity": "desert", "nature": "desert", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Antananarivo", "type": "cald", "activity": "cultura", "nature": "dealuri", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Victoria (Seychelles)", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Port Louis", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Male", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Mombasa", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Zanzibar City", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Stone Town", "type": "cald", "activity": "istorie", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Bazaruto", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Victoria Falls Town", "type": "cald", "activity": "aventura", "nature": "cascade", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Livingstone", "type": "cald", "activity": "aventura", "nature": "cascade", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Seychelles", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Mauritius", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Reunion", "type": "cald", "activity": "munte", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Madagascar Coast", "type": "cald", "activity": "aventura", "nature": "ocean", "budget": "mic", "region": "Africa & Altele"},
    {"name": "Santo Domingo", "type": "cald", "activity": "istorie", "nature": "plaja", "budget": "mic", "region": "Africa & Altele"},
    {"name": "San Juan (Puerto Rico)", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Papeete", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Tahiti", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Bora Bora", "type": "cald", "activity": "lux", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Fiji Islands", "type": "cald", "activity": "surfing", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Tonga", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Samoa", "type": "cald", "activity": "surfing", "nature": "ocean", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Vanuatu", "type": "cald", "activity": "aventura", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "New Caledonia", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Tahaa", "type": "cald", "activity": "lux", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Moorea", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Galapagos Islands", "type": "cald", "activity": "natura", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Easter Island", "type": "moderat", "activity": "istorie", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Bali (Oceania)", "type": "cald", "activity": "yoga", "nature": "jungla", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Papua New Guinea", "type": "cald", "activity": "aventura", "nature": "jungla", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Solomon Islands", "type": "cald", "activity": "plaja", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Falkland Islands", "type": "rece", "activity": "aventura", "nature": "insula", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Greenland", "type": "rece", "activity": "aventura", "nature": "ghetar", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Iceland", "type": "rece", "activity": "geotermal", "nature": "ghetar", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Reykjavik", "type": "rece", "activity": "geotermal", "nature": "ghetar", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Bergen", "type": "moderat", "activity": "fjord", "nature": "munte", "budget": "mediu", "region": "Africa & Altele"},
    {"name": "Oslo", "type": "rece", "activity": "cultura", "nature": "munte", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Stockholm", "type": "rece", "activity": "cultura", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Helsinki", "type": "rece", "activity": "cultura", "nature": "insula", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Copenhagen", "type": "moderat", "activity": "cultura", "nature": "coasta", "budget": "lux", "region": "Africa & Altele"},
    {"name": "Auckland (NZ)", "type": "moderat", "activity": "navigatie", "nature": "vulcani", "budget": "lux", "region": "Africa & Altele"},

]

TOP_CITIES = sorted([d["name"] for d in DESTINATIONS])