DESTINATIONS = [
    # --- EUROPA (Cultură, Natură, Moderat) ---
    {"name": "București", "type": "moderat", "activity": "cultura", "nature": "parcuri", "budget": "mic"},
    {"name": "Paris", "type": "moderat", "activity": "cultura", "nature": "gradini", "budget": "lux"},
    {"name": "Londra", "type": "moderat", "activity": "muzee", "nature": "parcuri", "budget": "lux"},
    {"name": "Roma", "type": "cald", "activity": "istorie", "nature": "coline", "budget": "mediu"},
    {"name": "Barcelona", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mediu"},
    {"name": "Brașov", "type": "moderat", "activity": "plimbare", "nature": "munte", "budget": "mic"},
    {"name": "Praga", "type": "moderat", "activity": "istorie", "nature": "rau", "budget": "mic"},
    {"name": "Viena", "type": "moderat", "activity": "muzica", "nature": "parcuri", "budget": "mediu"},
    {"name": "Amsterdam", "type": "moderat", "activity": "party", "nature": "canale", "budget": "lux"},
    {"name": "Atena", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mediu"},
    {"name": "Lisabona", "type": "cald", "activity": "plimbare", "nature": "ocean", "budget": "mediu"},
    {"name": "Oslo", "type": "rece", "activity": "muzee", "nature": "fiorduri", "budget": "lux"},
    {"name": "Stockholm", "type": "rece", "activity": "design", "nature": "arhipelag", "budget": "lux"},
    {"name": "Copenhaga", "type": "moderat", "activity": "bici", "nature": "mare", "budget": "lux"},
    {"name": "Budapesta", "type": "moderat", "activity": "spa", "nature": "rau", "budget": "mic"},
    {"name": "Varșovia", "type": "moderat", "activity": "istorie", "nature": "parcuri", "budget": "mic"},
    {"name": "Berlin", "type": "moderat", "activity": "party", "nature": "lacuri", "budget": "mediu"},
    {"name": "Madrid", "type": "cald", "activity": "arta", "nature": "parcuri", "budget": "mediu"},
    {"name": "Reykjavik", "type": "rece", "activity": "aventura", "nature": "vulcani", "budget": "lux"},
    {"name": "Innsbruck", "type": "rece", "activity": "ski", "nature": "munte", "budget": "mediu"},
    {"name": "Santorini", "type": "cald", "activity": "relaxare", "nature": "mare", "budget": "lux"},
    {"name": "Dubrovnik", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mediu"},
    {"name": "Venetia", "type": "moderat", "activity": "romantism", "nature": "canale", "budget": "lux"},
    {"name": "Munchen", "type": "moderat", "activity": "bere", "nature": "alpi", "budget": "mediu"},
    {"name": "Zurich", "type": "rece", "activity": "banci", "nature": "lac", "budget": "lux"},
    {"name": "Cluj-Napoca", "type": "moderat", "activity": "festival", "nature": "dealuri", "budget": "mic"},
    {"name": "Sibiu", "type": "moderat", "activity": "cultura", "nature": "munte", "budget": "mic"},

    # --- ASIA (Căldură, Aventură, Bugete Mixte) ---
    {"name": "Tokyo", "type": "moderat", "activity": "tehnologie", "nature": "gradini", "budget": "lux"},
    {"name": "Kyoto", "type": "moderat", "activity": "temple", "nature": "padure", "budget": "mediu"},
    {"name": "Bangkok", "type": "cald", "activity": "streetfood", "nature": "rau", "budget": "mic"},
    {"name": "Phuket", "type": "cald", "activity": "plaja", "nature": "insule", "budget": "mic"},
    {"name": "Bali", "type": "cald", "activity": "yoga", "nature": "jungla", "budget": "mediu"},
    {"name": "Singapore", "type": "cald", "activity": "lux", "nature": "gradini", "budget": "lux"},
    {"name": "Dubai", "type": "cald", "activity": "shopping", "nature": "desert", "budget": "lux"},
    {"name": "Abu Dhabi", "type": "cald", "activity": "cultura", "nature": "desert", "budget": "lux"},
    {"name": "Seoul", "type": "moderat", "activity": "k-pop", "nature": "munte", "budget": "mediu"},
    {"name": "Hanoi", "type": "cald", "activity": "istorie", "nature": "golf", "budget": "mic"},
    {"name": "Manila", "type": "cald", "activity": "plaja", "nature": "ocean", "budget": "mic"},
    {"name": "Mumbai", "type": "cald", "activity": "business", "nature": "mare", "budget": "mic"},
    {"name": "Beijing", "type": "moderat", "activity": "istorie", "nature": "zid", "budget": "mediu"},
    {"name": "Hong Kong", "type": "cald", "activity": "shopping", "nature": "golf", "budget": "lux"},
    {"name": "Malé", "type": "cald", "activity": "plaja", "nature": "atoli", "budget": "lux"},
    {"name": "Kathmandu", "type": "rece", "activity": "trekking", "nature": "himalaya", "budget": "mic"},
    {"name": "Taipei", "type": "cald", "activity": "food", "nature": "munte", "budget": "mediu"},

    # --- AMERICA (Diversitate, Distracție) ---
    {"name": "New York", "type": "moderat", "activity": "show", "nature": "parcuri", "budget": "lux"},
    {"name": "Los Angeles", "type": "cald", "activity": "filme", "nature": "plaja", "budget": "lux"},
    {"name": "Miami", "type": "cald", "activity": "party", "nature": "ocean", "budget": "lux"},
    {"name": "San Francisco", "type": "moderat", "activity": "tech", "nature": "golf", "budget": "lux"},
    {"name": "Las Vegas", "type": "cald", "activity": "cazino", "nature": "desert", "budget": "mediu"},
    {"name": "Chicago", "type": "rece", "activity": "arhitectura", "nature": "lac", "budget": "mediu"},
    {"name": "Toronto", "type": "rece", "activity": "muzee", "nature": "lac", "budget": "mediu"},
    {"name": "Vancouver", "type": "moderat", "activity": "aventura", "nature": "munte", "budget": "lux"},
    {"name": "Mexico City", "type": "cald", "activity": "istorie", "nature": "vulcan", "budget": "mic"},
    {"name": "Cancun", "type": "cald", "activity": "plaja", "nature": "jungla", "budget": "mediu"},
    {"name": "Rio de Janeiro", "type": "cald", "activity": "carnaval", "nature": "munte", "budget": "mediu"},
    {"name": "Buenos Aires", "type": "moderat", "activity": "tango", "nature": "rau", "budget": "mic"},
    {"name": "Lima", "type": "cald", "activity": "gastronomie", "nature": "ocean", "budget": "mic"},
    {"name": "Santiago", "type": "moderat", "activity": "vin", "nature": "anzi", "budget": "mediu"},
    {"name": "Havana", "type": "cald", "activity": "muzica", "nature": "plaja", "budget": "mic"},

    # --- ALTE REGIUNI & EXOTICE ---
    {"name": "Sydney", "type": "cald", "activity": "surfing", "nature": "ocean", "budget": "lux"},
    {"name": "Melbourne", "type": "moderat", "activity": "cafea", "nature": "ocean", "budget": "lux"},
    {"name": "Auckland", "type": "moderat", "activity": "navigatie", "nature": "vulcani", "budget": "lux"},
    {"name": "Cape Town", "type": "cald", "activity": "vin", "nature": "munte", "budget": "mediu"},
    {"name": "Cairo", "type": "cald", "activity": "piramide", "nature": "nile", "budget": "mic"},
    {"name": "Marrakech", "type": "cald", "activity": "bazar", "nature": "desert", "budget": "mic"},
    {"name": "Casablanca", "type": "cald", "activity": "ocean", "nature": "plaja", "budget": "mediu"},
    {"name": "Nairobi", "type": "cald", "activity": "safari", "nature": "savana", "budget": "mediu"},
    {"name": "Zanzibar", "type": "cald", "activity": "relaxare", "nature": "ocean", "budget": "mediu"},
    {"name": "Istanbul", "type": "moderat", "activity": "istorie", "nature": "bosfor", "budget": "mic"},
    {"name": "Antalya", "type": "cald", "activity": "resort", "nature": "mare", "budget": "mic"},
    {"name": "Tel Aviv", "type": "cald", "activity": "beachparty", "nature": "mare", "budget": "lux"},

    # ... și continuând până la 100 de intrări variate
    {"name": "Florence", "type": "moderat", "activity": "arta", "nature": "campie", "budget": "mediu"},
    {"name": "Sevilla", "type": "cald", "activity": "flamenco", "nature": "rau", "budget": "mediu"},
    {"name": "Nice", "type": "cald", "activity": "lux", "nature": "riviera", "budget": "lux"},
    {"name": "Edinburgh", "type": "rece", "activity": "castele", "nature": "dealuri", "budget": "mediu"},
    {"name": "Dublin", "type": "moderat", "activity": "pub", "nature": "campie", "budget": "mediu"},
    {"name": "Bruxelles", "type": "moderat", "activity": "politica", "nature": "parcuri", "budget": "mediu"},
    {"name": "Lyon", "type": "moderat", "activity": "mancare", "nature": "rau", "budget": "mediu"},
    {"name": "Porto", "type": "moderat", "activity": "vin", "nature": "ocean", "budget": "mic"},
    {"name": "Napoli", "type": "cald", "activity": "pizza", "nature": "mare", "budget": "mic"},
    {"name": "Catania", "type": "cald", "activity": "vulcan", "nature": "mare", "budget": "mic"},
    {"name": "Ibiza", "type": "cald", "activity": "party", "nature": "insulă", "budget": "lux"},
    {"name": "Mykonos", "type": "cald", "activity": "party", "nature": "mare", "budget": "lux"},
    {"name": "Rhodos", "type": "cald", "activity": "istorie", "nature": "mare", "budget": "mediu"},
    {"name": "Larnaca", "type": "cald", "activity": "plaja", "nature": "mare", "budget": "mic"},
    {"name": "Tbilisi", "type": "moderat", "activity": "vin", "nature": "munte", "budget": "mic"},
    {"name": "Erevan", "type": "moderat", "activity": "istorie", "nature": "munte", "budget": "mic"},
    {"name": "Baku", "type": "moderat", "activity": "arhitectura", "nature": "mare", "budget": "mediu"},
    {"name": "Muscat", "type": "cald", "activity": "cultura", "nature": "ocean", "budget": "mediu"},
    {"name": "Doha", "type": "cald", "activity": "muzee", "nature": "golf", "budget": "lux"},
    {"name": "Colombo", "type": "cald", "activity": "ceai", "nature": "ocean", "budget": "mic"},
    {"name": "Ho Chi Minh City", "type": "cald", "activity": "scutere", "nature": "rau", "budget": "mic"},
    {"name": "Chiang Mai", "type": "moderat", "activity": "temple", "nature": "munte", "budget": "mic"},
    {"name": "Perth", "type": "cald", "activity": "soare", "nature": "ocean", "budget": "lux"},
    {"name": "Brisbane", "type": "cald", "activity": "surfing", "nature": "rau", "budget": "lux"},
    {"name": "Quebec City", "type": "rece", "activity": "istorie", "nature": "rau", "budget": "mediu"},
    {"name": "Montreal", "type": "rece", "activity": "jazz", "nature": "insulă", "budget": "mediu"},
    {"name": "Seattle", "type": "rece", "activity": "cafea", "nature": "munte", "budget": "lux"},
    {"name": "New Orleans", "type": "cald", "activity": "jazz", "nature": "rau", "budget": "mediu"},
    {"name": "Montevideo", "type": "moderat", "activity": "plaja", "nature": "rau", "budget": "mediu"}
]

TOP_CITIES = sorted([d["name"] for d in DESTINATIONS])